### ISSUE TITLE
Add an option to perform case-sensitive relative path check.

### ISSUE THREAD

**Issue by nzubair** [vors/MarkdownLinkCheck#2]
Came across the need for this while looking at PowerShell-Docs repo. Some of the files do not have properly cased links in the SEE ALSO section. 

For example, the links at the bottom of [about_Aliases.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Core/About/about_Aliases.md) are lowercased. They are valid on Windows but on Github, they're broken.

**Comment by vors** [comment]
should be addressed by #6
